// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV7WJIDp6Ckp_3d_qMXsf12GgKwweD7IY',
    appId: '1:925756921213:web:ad970f7633284c1736a814',
    messagingSenderId: '925756921213',
    projectId: 'chess-c3dc3',
    authDomain: 'chess-c3dc3.firebaseapp.com',
    storageBucket: 'chess-c3dc3.firebasestorage.app',
    measurementId: 'G-GCYLCSJ8BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCym_gtRTtFb-dSl77ho8IhAU9vOysAfmQ',
    appId: '1:925756921213:android:43f20c646cb881b336a814',
    messagingSenderId: '925756921213',
    projectId: 'chess-c3dc3',
    storageBucket: 'chess-c3dc3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV7WJIDp6Ckp_3d_qMXsf12GgKwweD7IY',
    appId: '1:925756921213:web:50ed657f5f519f6436a814',
    messagingSenderId: '925756921213',
    projectId: 'chess-c3dc3',
    authDomain: 'chess-c3dc3.firebaseapp.com',
    storageBucket: 'chess-c3dc3.firebasestorage.app',
    measurementId: 'G-5YGB9XR8LF',
  );
}
